language: java

addons:
  sonarcloud:
    organization: "petruki"
    token: ${SONAR_TOKEN}

cache:
  directories:
  - $HOME/.m2
      
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=switcher-client-java